site_name: Deployment Documentation
nav:
    - Config Documentation: index.md
    - Basic Installation: installation.md
    - Site Rules Specification: site-rules-specs.md
    - Flashing Instructions: flash.md
    - Camera Calibration: camera-calibration.md
    - Utilities: utilities.md
theme: readthedocs
